### ISSUE TITLE
JAVA class notfound exception 

### ISSUE THREAD

**Issue by kishoresoma007** [target/plugin-for-rundeck-to-execute-sap-modules#4]
we have downloaded the sapjco3.jar file form sap and update the path in Pluginconfigurations.java (private String jcoPath = "/var/tmp/sapjco3.jar";) also updated the path in build.gradle (  compile files("/var/tmp/sapjco3.jar")), 
after compiling with gradle (gradlew clean build), copied rundeck-sapplugin.jar file in to rundeck/libext folder, we were able to create job, but when we run it, it gives JAVA CLASS not found error. 

ailed executing step plugin [SapWorkflowStepPlugin]: java.lang.NoClassDefFoundError: com/sap/conn/jco/JCoException
	at org.rundeck.plugins.sap_connector.SapManager.SapConnector(SapManager.java:22)
	at org.rundeck.plugins.SapWorkflowStepPlugin.executeStep(SapWorkflowStepPlugin.java:165)
	at com.dtolabs.rundeck.core.execution.workflow.steps.StepPluginAdapter.executeWorkflowStep(StepPluginAdapter.java:109)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:111)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:285)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:681)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:76)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:32)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$beginOperation$1(WorkflowEngineOperationsProcessor.java:323)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.sap.conn.jco.JCoException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:58)
	at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:44)
	... 16 more
1: Workflow step finished, result: PluginFailed: com/sap/conn/jco/JCoException
[workflow] Finish step: 1,SapWorkflowStepPlugin

Please help, we have tried many things, but stil same issue.

**Comment by colloque** [comment]
Hello,
I am interesting for this resolution ?

D id you get feedback ?

Thanks
